FROM docker.io/nixos/nix:latest

RUN apk add --no-cache qemu-aarch64-static

RUN mkdir -p /etc/nix && \
    echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf && \
    echo "extra-platforms = aarch64-linux" >> /etc/nix/nix.conf && \
    echo "sandbox = false" >> /etc/nix/nix.conf

WORKDIR /build

CMD ["nix", "build", ".#raspi5", "-o", "result-sd"]
